# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Desktop/smart_password_lock/smart_password_lock.srcs/sources_1/ip/clock_PLL_100_50_25MHz/clock_PLL_100_50_25MHz.xci
# IP: The module: 'clock_PLL_100_50_25MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/smart_password_lock/smart_password_lock.gen/sources_1/ip/clock_PLL_100_50_25MHz/clock_PLL_100_50_25MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_PLL_100_50_25MHz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Desktop/smart_password_lock/smart_password_lock.gen/sources_1/ip/clock_PLL_100_50_25MHz/clock_PLL_100_50_25MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_PLL_100_50_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Desktop/smart_password_lock/smart_password_lock.gen/sources_1/ip/clock_PLL_100_50_25MHz/clock_PLL_100_50_25MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_PLL_100_50_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Desktop/smart_password_lock/smart_password_lock.srcs/sources_1/ip/clock_PLL_100_50_25MHz/clock_PLL_100_50_25MHz.xci
# IP: The module: 'clock_PLL_100_50_25MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/smart_password_lock/smart_password_lock.gen/sources_1/ip/clock_PLL_100_50_25MHz/clock_PLL_100_50_25MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_PLL_100_50_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Desktop/smart_password_lock/smart_password_lock.gen/sources_1/ip/clock_PLL_100_50_25MHz/clock_PLL_100_50_25MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_PLL_100_50_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Desktop/smart_password_lock/smart_password_lock.gen/sources_1/ip/clock_PLL_100_50_25MHz/clock_PLL_100_50_25MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_PLL_100_50_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
