######################################################################
#
# File name : bcd_tb_wave.do
# Created on: Sat Oct 14 21:12:02 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
