######################################################################
#
# File name : bcd_tb_compile.do
# Created on: Sat Oct 14 21:14:03 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modelsim\\win64\\vlib modelsim_lib/work
D:\\modelsim\\win64\\vlib modelsim_lib/msim

D:\\modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim\\win64\\vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../smart_password_lock.srcs/sources_1/new/bcd_view_out.v" \
"../../../../smart_password_lock.srcs/sim_1/new/bcd_tb.v" \


# compile glbl module
D:\\modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

