######################################################################
#
# File name : bcd_tb.udo
# Created on: Sat Oct 14 21:12:02 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
