######################################################################
#
# File name : bcd_tb_tb_compile.do
# Created on: Sun Oct 15 00:23:46 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modelsim\\win64\\vlib modelsim_lib/work
D:\\modelsim\\win64\\vlib modelsim_lib/msim

D:\\modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim\\win64\\vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../smart_password_lock.srcs/sources_1/new/bcd.v" \
"../../../../smart_password_lock.srcs/sources_1/new/bcd_view_out.v" \
"../../../../smart_password_lock.srcs/sources_1/new/display_decode.v" \
"../../../../smart_password_lock.srcs/sources_1/new/frequency_division.v" \
"../../../../smart_password_lock.srcs/sim_1/new/bcd_tb_tb.v" \


# compile glbl module
D:\\modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

