######################################################################
#
# File name : bcd_tb_tb_wave.do
# Created on: Sun Oct 15 00:21:35 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
