######################################################################
#
# File name : bcd_tb_tb.udo
# Created on: Sun Oct 15 00:21:35 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
