######################################################################
#
# File name : Hz_tb_wave.do
# Created on: Tue Nov 14 08:22:13 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
