######################################################################
#
# File name : Hz_tb.udo
# Created on: Tue Nov 14 08:22:13 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
