######################################################################
#
# File name : password_in_tb_wave.do
# Created on: Thu Nov 09 08:31:57 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
