######################################################################
#
# File name : password_in_tb.udo
# Created on: Thu Nov 09 08:31:57 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
