set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN G17 [get_ports rx]
set_property PACKAGE_PIN E18 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports rx]

set_property IOSTANDARD LVCMOS33 [get_ports {dout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]
set_property PACKAGE_PIN T10 [get_ports {dout[6]}]
set_property PACKAGE_PIN R10 [get_ports {dout[5]}]
set_property PACKAGE_PIN K16 [get_ports {dout[4]}]
set_property PACKAGE_PIN K13 [get_ports {dout[3]}]
set_property PACKAGE_PIN P15 [get_ports {dout[2]}]
set_property PACKAGE_PIN T11 [get_ports {dout[1]}]
set_property PACKAGE_PIN L18 [get_ports {dout[0]}]
set_property PACKAGE_PIN U13 [get_ports {sel[7]}]
set_property PACKAGE_PIN K2 [get_ports {sel[6]}]
set_property PACKAGE_PIN T14 [get_ports {sel[5]}]
set_property PACKAGE_PIN P14 [get_ports {sel[4]}]
set_property PACKAGE_PIN J14 [get_ports {sel[3]}]
set_property PACKAGE_PIN T9 [get_ports {sel[2]}]
set_property PACKAGE_PIN J18 [get_ports {sel[1]}]
set_property PACKAGE_PIN J17 [get_ports {sel[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports display]
set_property PACKAGE_PIN P18 [get_ports display]

set_property IOSTANDARD LVCMOS33 [get_ports led_change]
set_property IOSTANDARD LVCMOS33 [get_ports led_no]
set_property IOSTANDARD LVCMOS33 [get_ports led_ok]
set_property IOSTANDARD LVCMOS33 [get_ports led_switch]

set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN M17 [get_ports rst]
set_property PACKAGE_PIN V11 [get_ports led_change]
set_property PACKAGE_PIN V12 [get_ports led_no]
set_property PACKAGE_PIN V14 [get_ports led_ok]

set_property PACKAGE_PIN V15 [get_ports led_switch]

set_property IOSTANDARD LVCMOS33 [get_ports change_password]
set_property IOSTANDARD LVCMOS33 [get_ports ok]
set_property PACKAGE_PIN N17 [get_ports change_password]
set_property PACKAGE_PIN M18 [get_ports ok]

set_property IOSTANDARD LVCMOS33 [get_ports beep]
set_property PACKAGE_PIN H14 [get_ports beep]
